import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import animeRouter from "./anime";
import mangaRouter from "./manga";
import reviewsRouter from "./reviews";
import chatRouter from "./chat";
import reportsRouter from "./reports";
import adminRouter from "./admin";
import watchlistRouter from "./watchlist";
import progressRouter from "./progress";
import recommendationsRouter from "./recommendations";
import profilesRouter from "./profiles";
import repliesRouter from "./replies";
import notificationsRouter from "./notifications";
import streamReportsRouter from "./stream-reports";
import proxyImageRouter from "./proxy-image";
import xpRouter from "./xp";

const router: IRouter = Router();

router.use(proxyImageRouter);
router.use(xpRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(animeRouter);
router.use(mangaRouter);
router.use(repliesRouter);
router.use(reviewsRouter);
router.use(chatRouter);
router.use(reportsRouter);
router.use(adminRouter);
router.use(watchlistRouter);
router.use(progressRouter);
router.use(recommendationsRouter);
router.use(profilesRouter);
router.use(notificationsRouter);
router.use(streamReportsRouter);

export default router;
